### ISSUE TITLE
Translation + Sharing

### ISSUE THREAD

**Issue by RaffiSapire** [Livepeer-Community-Node/Grant-Program#3]
Help expand the community by introducing the project to enthusiasts in your country or who speak your language. A campaign to share the translated document is a requisite part of this grant because we want to make sure your hard work delivers real world results! 

**Goal**
Expand the community by translating key documents into a new language, and hosting online and in person events around this goal 

**Steps**
Specify the content to translate
Translate and user test with 2 people 
Share feedback back with us 
Identify 5 communities with whom you could share this translated content. We suggest Ethereum meetups, facebook groups, telegram groups. 
Share the paper with each group
Bonus + 50 LPT : schedule an online webinar or in person event where you discuss how Livepeer works. We are happy to help you prep for this and empower you to represent the project! 

**Apply**
Comment on this issue with 1) the content you want to translate 2) your timeline and milestones 3) how much time you anticipate it taking 4) what groups you plan to share this with (with links to the communities)

**Comment by felipegaucho** [comment]
## 🇧🇷 Content Localisation Effort | Brazil

### Objective:
To provide the Portuguese speaking community with reasonably comprehensive introductory material (text, video and social context) to start interacting with Livepeer.

### Why Brazil?
It has a notable videodev community ([Globo](https://opensource.globo.com/)) & audiovisual industry.
Big crypto-mining players with GPU [farms in Paraguay](https://bitcoinnews.com/the-golden-gooses-bitcoin-egg-worlds-largest-mining-farm-in-paraguay/)/Iguazu.
Country has reportedly [more crypto-investors](https://www.forbes.com/sites/kenrapoza/2018/05/30/more-people-opening-crypto-trading-accounts-in-brazil-than-traditional-securities/) than stock buyers already (~2m people).
We have a tech hub with a [EOS Block Producer in Rio](https://web.eosrio.io/), who knows what are their plans for serving other networks...

### Steps:
1⃣ **21/01** - Making a **new "[Livepeer 101](https://www.youtube.com/watch?v=Y_lammvup8M&t=5s)" video**, in the same style of the existing one (audio + slides narrated in slightly informal way) with minor updates to reflect Streamflow changes (e.g. the Orchestrator role) - **in Portuguese** (slides/video could be reused if you wanted to do an English version at some point).
2⃣ **25/01** - **Translation of the** "**Video Miner - A Path to Scaling Video Transcoding**" text to Portuguese, with **adaptations to make it appeal more to those who do or manage GPU mining**.
3⃣ **03/02** - **Translation of the [Streamflow whitepaper]**(https://github.com/livepeer/wiki/blob/master/STREAMFLOW.md) into Portuguese.

4⃣ **10/02** - Writing a press release with the goal of being published on at least 2 proeminent local crypto-media + reported in 1 Brazilian youtuber/influencer video, about the Streamflow upgrade, what the Livepeer network has achieved so far, overall stats, defining moments (events), and what the community expects to come (likely with interviews w/ 2-4 random community members).
5⃣ **25/01 <-> 14/02 (TBD)** - 20min-presenting Livepeer's inner workings on a [local Ethereum meetup](https://www.meetup.com/ethereum_sp/).

- "Video Miner" text to be published on a local crypto media outlet.
- "101" Video will be embedded in these publications, and sent to Livepeer for YT publishing.
- News / press release results will be reported via Discord or this issue.
- Translated whitepaper to be linked via the PR/press, and sent to Livepeer for Github publishing.
- Can't ensure the meetup will be recorded (I'll take pics). Interested attendees will be directed to the Livepeer Discord.


### ⏰ Estimated completion date:
**2nd week of February 19** (last milestone subject to external factors, can take up to 3 weeks more).

### Estimated potential reach:
240 million people ([Portuguese speakers](https://en.wikipedia.org/wiki/Portuguese_language) worldwide).

### Estimated actual impact:
~50-100 people face-to-face.
~30.000-200.000 views/UVs/"reads" (as Medium counts) on online content (text & sum of earned media).

### 🔗 Communities to share:
- [Ethereum Sao Paulo MeetUp](https://www.meetup.com/ethereum_sp/);
- [Ethereum Brasil Facebook Group](https://www.facebook.com/groups/ethereum.brasil) (+ [2 similar](https://www.facebook.com/groups/1137809083017105) [dev-oriented groups](https://www.facebook.com/groups/ethdevbr));
- [Crypto-mining Brasil Facebook Group](https://www.facebook.com/groups/mineracaodecriptomoedas/); 
- [Bitcoin Brasil Facebook Group](https://www.facebook.com/groups/btcbr);
- [BitcoinTalk Portuguese subforum](https://bitcointalk.org/index.php?board=29.0);
- Options of local crypto-media outlet ([1](https://www.criptomoedasfacil.com/representante-da-paradigma-capital-diz-que-icos-nao-devem-ser-vistas-por-empresas-que-buscam-financiamento/), [2](https://livecoins.com.br/), [3](https://portaldobitcoin.com), [4](https://radarbtc.com.br)).
- Options of local crypto-Youtubers ([1](https://www.youtube.com/channel/UC8n6k3YWf4b4k0FBVvtDGrg), [2](https://www.youtube.com/channel/UCLJkh3QjHsLtK0LZFd28oGg), [3](https://www.youtube.com/channel/UC549xKR8JvVXLNHvzV_AZsw), [4](https://www.youtube.com/channel/UCUCcZA8gPcl01ilAxoZniwg)).

### Suggested metrics to gauge impact:
- New GitHub stars/follows/issues/PRs on Livepeer repos after the effort.
- Visits from Brazil/Portugal on Livepeer's website.
- Unique visitors in texts on the media (I can write down here a little report w/ links and data 1-2 weeks after completion).
- (?) New transcoding nodes on the network.

----------------------------------

**Please let me know:**

- If this makes sense at all or not --> idea was to package some stuff that offer a good intro. to Livepeer for potential transcoders/orchestrators; developers; and the crypto-aware public, so that some people can start organising and experimenting by themselves outside the English speaking realm only.
- What can be the expected grant (or range).
- Suggestions to make the deliverables more compelling/useful (more or less of them) --> maybe translating the whitepaper is an overkill (most people who dig into it are likely used to English documentation), but figured it'd be important for you guys in the mid-term.

**Comment by RaffiSapire** [comment]
Great, thank you @felipegaucho! We are so excited about this. 

We are pleased to grant you a 600 LPT grant for the first Milestone:
- 25/01 (5-6hr work): Publication of the translation of the "Video Miner" text (local media section).
- 03/02 (12-15hr work): Finishing translation of Streamflow whitepaper.
- 07/02 (3-4hr work): Video re-recording/adaptation (requested access to GDoc to comment).

And an additional 700 LPT for the second Milestone:
- 10/02 (5-7hr work): 2x PR/Story publication on media.
- Between 20/01 - 10/02 (3-4hr work): Meetup presentation. 

Could we check in in early-mid Jan on Milestone 1, please?

**Comment by felipegaucho** [comment]
Sounds good @RaffiSapire!

Sure, I'll come back with an update (on this issue) on Jan/16 (let me know if it doesn't work for any reason).

[I requested access to the [GoogleDoc mentioned above](https://docs.google.com/document/d/1I_Lwzln-GF-0x24SeVv_MYm8bZdsX9L1SdgJU8UFIm4/edit) under a _felipe.santana at bossa..._ email address - permission was not given yet]

**Comment by felipegaucho** [comment]
Hi @RaffiSapire ,

a bit of a late update here:

- ✅ **25/01** (completed **_28/01_**): https://livecoins.com.br/o-que-fazer-com-suas-gpus-alem-de-apostar-na-criptomoeda-grin -> used some images from Philippe's recent presentation in Sweden; framed things in the context of a revamped interest on GPU mining (Grin & co.); compilated some resources/links & info. on the token side of things. Non-formatted text [is here](https://docs.google.com/document/d/1aZAuGTvl4gWucB21C_V_vWev7KVmtUnt1ChQBdfwAUM/edit?usp=sharing). Might be picked up by some other channels still. 
[_Some sharing_:
[https://bitcointalk.org/index.php?topic=5103330](https://bitcointalk.org/index.php?topic=5103330) |  [www.facebook.com/groups/ethereum.brasil/permalink/2290666924483837](www.facebook.com/groups/ethereum.brasil/permalink/2290666924483837)  |   [https://web.telegram.org/#/im?p=@paratiivideo](https://web.telegram.org/#/im?p=@paratiivideo)   |   [https://www.facebook.com/groups/btcbr/permalink/2414346751908812](https://www.facebook.com/groups/btcbr/permalink/2414346751908812)]

- 🕑 **03/02** (on track so far - will be pushing updates [to this fork](https://github.com/felipegaucho/wiki-1/blob/master/STREAMFLOW.md)): Streamflow WP translation (PT-BR).

- ✋ **07/02** (still haven't begun): 101 video re-recording (PT-BR).

**Comment by RaffiSapire** [comment]
Sounds great, thanks Felipe!

**Comment by felipegaucho** [comment]
Hi @RaffiSapire ,

update:

* ✅ **25/01** (completed **_28/01_**): [Video Miner text localisation + publication on media](https://livecoins.com.br/o-que-fazer-com-suas-gpus-alem-de-apostar-na-criptomoeda-grin)
* ✅ **03/02** (completed **_19/02_**): [Streamflow WP translation (PT-BR)](https://github.com/felipegaucho/wiki-1/blob/master/STREAMFLOW.md)
* ✋ **07/02** (still haven't begun): 101 video re-recording (PT-BR).

This 3rd one should be done by tomorrow or Friday.

**Comment by GreyEcologist** [comment]
###  🇫🇷 Content Localization Effort | French

Hi @RaffiSapire, I'm proposing a french localization effort based on Felipe's:

### 🎯 Objective:
To provide the French speaking community with a comprehensive introduction to Livepeer and the Streamflow proposal.

###  🇫🇷 Why French?
* French is the official language in 29 countries across multiple continents.
* 84 countries are part of the International Organization of the Francophonie, and use French as a franca lingua.
* There are 235 million [French speakers](https://en.wikipedia.org/wiki/French_language) people in the world.
* French is one of the most influential languages widely used in the worlds of journalism and business.

### ⏰ Timeframe:

Estimated total timeframe of 6 weeks for the project's completion:

| Timeframe  | Goal |
| ------------- | ------------- |
| 2 weeks  | **Translation of the** [Livepeer white paper](https://github.com/livepeer/wiki/blob/master/WHITEPAPER.md) into French  |
| 2 weeks  | **Translation of the** [Streamflow white paper](https://github.com/livepeer/wiki/blob/master/STREAMFLOW.md) into French  |
| 1 week  | **new "[Livepeer 101](https://www.youtube.com/watch?v=Y_lammvup8M&t=5s)" video** updated with Streamflow in French  |
| 1 week | Write a press release to be published in multiple french crypto-media  |

* "Video Miner" text to be published on french crypto media outlet.
* "101" Video will be embedded in these publications, and sent to Livepeer.
* Media results will be reported via Discord or this issue.
* Translated white paper to be linked via the PR/article, and sent to Livepeer.

### 🌎 Estimated impact:
- 100+ reads of the white papers
- 1000+ reads of the press release
- 10,000+ views of the video

### 🔗 Communities to share:
* [Cryptonews - french crypto news outlet](https://fr.cryptonews.com/)
* [Ethereum France - french ethereum news ](https://www.ethereum-france.com/)
* [Ethereum France - Facebook Group](https://www.facebook.com/ethereumfrance/)
* [Ethereum Community - Forum](https://forum.ethereum.org/categories/french)
* [Crypto-mining - Forum](https://bitcointalk.org/index.php?board=48.0)
* [Ethereum Paris - MeetUp group](https://www.meetup.com/Ethereum-Paris/)
* [Bitcoin.fr - Youtube (10k subscribers)](https://www.youtube.com/user/marco44nantes)
* [Journal du Coin - Youtube (20k subscribers)](https://www.youtube.com/channel/UC7qnB0XxzOEwWWn9Q6HPmCw)
* [Bitcoin France - Telegram (2k members)](https://t.me/BitcoinFranceClub)
* [Ethereum Francophone - Telegram (1k members)](https://t.me/ethereumfrance)

**Comment by felipegaucho** [comment]
Hi @RaffiSapire,

🎆 **update: 1st milestone is done.**

* ✅ **25/01** (completed **_28/01_**): [Video Miner text localisation + publication on media](https://livecoins.com.br/o-que-fazer-com-suas-gpus-alem-de-apostar-na-criptomoeda-grin)
* ✅ **03/02** (completed **_19/02_**): [Streamflow WP translation (PT-BR)](https://github.com/felipegaucho/wiki-1/blob/master/STREAMFLOW.md)
* ✅ **07/02** (completed: **_25/02_**): 101 video re-recording (PT-BR), [on Youtube, unlisted](https://youtu.be/sP_RgBZ6lJQ) and [on GDrive](https://drive.google.com/file/d/1aNsqq2PHQFgBwTFfu5gZMC9R5-YMu7hb/view?usp=sharing). The text/translation itself [is here](https://docs.google.com/document/d/1CW_-3U6OYaqKxifgelOk9fXkhx7QWTFcPgaFy5iXjDY/edit?usp=sharing).

I'm now going into the 2nd milestone (Media x2 + MeetUp). Video and translated paper will go into the media story + serve as intro material to meetup attendees. I will come back soon w/ updates regarding this final part of the bounty.

**Comment by RaffiSapire** [comment]
@felipegaucho awesome! let me know your eth address to send LPT to?

**Comment by RaffiSapire** [comment]
Also @felipegaucho are you able to share back some photos from the event next week? Would love to share on social media.

**Comment by RaffiSapire** [comment]
Hey @GreyEcologist 
Thank you for your proposal! We're excited to have content in French. A few questions and suggestions: 

M1 
- Wondering if you should do Streamflow but not the original whitepaper since it is outdated, what do you think? 
- Video miner text isn't in your timeframe but I noticed you mention it later on. Is this something you are translating?
- Livepeer 101 video - here, are you going to make your own slides, record, edit, and voiceover? Please do share the script!
- How did you arrive at these suggested items things to translate? As a community member do you feel like they've been most helpful? 

M2 
- Press release is written in French - where will the press release be distributed?
- Sharing about the project in 10 french communities (listed above) - some of these are forums, some are youtube channels, some are meetups. For each type, are you posting in the comments, or are you getting the channel to cover it, or how are you thinking about the distribution there, and what the goals are?

**Comment by felipegaucho** [comment]
This is it @RaffiSapire : 

0xAE8cC9ad66Fc9f88AbE8D268383f51DC39Cf202e
[starts with 0xAE - ends with 202e]

Yes, I'll come back w/ pics from the event next week! :)

**Comment by GreyEcologist** [comment]
Hi @RaffiSapire:

**M1**
 

> Wondering if you should do Streamflow but not the original whitepaper since it is outdated, what do you think?
 
That was something I wondered as well, whether I should only read the Streamflow, but I ended up reading both, and it seems to me that the Streamflow is complementary to the original white paper.  I’m happy to only translate the Streamflow WP, but in my opinion, the original WP is still valuable.

> Video miner text isn't in your timeframe but I noticed you mention it later on. Is this something you are translating?

Sorry, I meant the Livepeer 101 video.

>  Livepeer 101 video - here, are you going to make your own slides, record, edit, and voiceover? Please do share the script!

I intend to use the existing slide and do a voiceover. French audiences are used to french subs over english material and especially in technology there is a lot of anglicism, so it’s very common. The only modification I planned for is to mentioned the orchestrators/streamflow update at the end of the video. I can share a script later this week.
 

> How did you arrive at these suggested items things to translate? As a community member do you feel like they've been most helpful?

For me the white papers were essential. I'd watched videos, read articles, and joined the discord and forum convos, but it wasn’t until I read the WPs that I really grasped the value proposition. I think videos are great for introduction, white papers are better for deep dives and really understand how Livepeer works.



**M2**

> Press release is written in French - where will the press release be distributed?

There’s a couple of french outlets that accept submission for press release (communique de presse) for crypto projects, ie:
https://cryptonaute.fr/presse/
http://www.24presse.com/depot/cp/index.php


> Sharing about the project in 10 french communities (listed above) - some of these are forums, some are youtube channels, some are meetups. For each type, are you posting in the comments, or are you getting the channel to cover it, or how are you thinking about the distribution there, and what the goals are?

My goal is to contact news outlets contributors to cover to the press release and write articles on StreamFlow, then share those articles in the forums/social media. Similarly, I’m looking to contact youtube video makers, have them cover streamFlow, and share the videos in the forums/social media. I will be in Paris this summer and I know a couple of locals that attend crypto events there, so I’ll be looking to make a presentation while I’m there.

**Comment by felipegaucho** [comment]
Hi @RaffiSapire, just pinging to get an expected date for payout as for Milestone 1 (11d ago). Milestone 2 still being worked on.

Best,

**Comment by GreyEcologist** [comment]
@RaffiSapire quick idea I wanted to add, and wondering what you think @felipegaucho: we could coordinate our translation efforts with respective discord channels, i.e a Brazil/Portuguese and a French channel.

**Comment by RaffiSapire** [comment]
@GreyEcologist @felipegaucho sure - totally open to adding those. Are you each on Livepeer's discord? Will you be hopping in and supporting any users who speak French / Portugues respectively? Will you be driving people to the discord from the content you create?

**Comment by RaffiSapire** [comment]
@GreyEcologist Thank you so much for your patience, and I'm sorry it took me a while to get back to you. We are pleased to grant you a 400 LPT grant for the first Milestone:
(12-15hr work): Finishing translation of Streamflow whitepaper.
(12-15 hr work): Translation of whitepaper.
(3-4hr work): Video re-recording/adaptation.

And additional LPT for the second Milestone:
Press: Articles are published in press (20 LPT each)
Distribution: Content shared in the 10 communities listed, with a goal of engagement - 2 comments / questions from community in each! 10 LPT each. 
Youtube: YouTube video makers w/ over 10K followers cover Streamflow / Livepeer in video  (50 LPT each)
Presentation / Meetup with 30+ people: 100 LPT

**Comment by GreyEcologist** [comment]
@RaffiSapire sounds good! 
- I'll get started and provide regular updates. 
- I am on the Livepeer Discord server, and I can keep an eye on the channel regularly.

**Comment by RaffiSapire** [comment]
@GreyEcologist for the script you sent, I dont know what it says. If you share in English I can provide comments to your questions.

**Comment by GreyEcologist** [comment]
Hi @RaffiSapire,
I've added the english translation to the documentation:
https://github.com/Livepeer-Community-Node/Grant-Program/issues/3#issuecomment-467453093

As far as the translation work is going, I've done the basic translation for the Livepeer WP, I'm finishing the one for the Streamflow WP. After that I will still need to do some formatting and linking. I should have another in a week or so.

Best.

**Comment by fedorello** [comment]
### 🇷🇺 Content Localization Effort | Russia
### 🎯 Objective:
Providing the Russian-speaking community with a comprehensive introduction to Livepeer and the Streamflow offer.

### Why Russia?
1⃣  Russian language is one of the most common in the world. [More than 250 million people](https://en.wikipedia.org/wiki/Geographical_distribution_of_Russian_speakers#Statistics) in various countries speak Russian.

2⃣  Russia has very cheap electricity and a cold climate. For example, in Irkutsk, 1 kWh costs about $ 0.015. This makes Russia very attractive for mining activities. Therefore, a rather impressive mining infrastructure (which can be used as transcoders) is already concentrated here.

3⃣  Interest in blockchain and cryptocurrency in Russia and in Russian-speaking countries (former CIS countries) is very high. This is evidenced by the fact that [the most active thread on the bitcointalk.org](https://bitcointalk.org/index.php?board=10.0) is Russian-speaking. [4,432,539 Posts and 118,164 Topics for today].

### ⏰ Timeframe:
Estimated total timeframe of 6 weeks for the project's completion:

- [ ] Translation of the [Livepeer white paper](https://github.com/livepeer/wiki/blob/master/WHITEPAPER.md) into Russian (~1 week)
- [ ] Translation of the [Streamflow white paper](https://github.com/livepeer/wiki/blob/master/STREAMFLOW.md) into Russian (~1 week)
- [ ] new ["Livepeer 101"](https://www.youtube.com/watch?v=Y_lammvup8M) video Will be translated into Russian (~1 week)
- [ ] ["Graph Day: Designing The Livepeer Protocol with Eric Tang"](https://www.youtube.com/watch?v=1lkoabVNHuQ) video will be translated into Russian (~1 week)
- [ ] Write a press release to be published in prominent russian crypto-media (2 weeks)

To realize all this, I plan to start YouTube channel on which I will post Livepeer-related videos translated into Russian. In the description of the video, I will add links to whitepaper in Russian and official information resources (Livepeer website, discord group, telegram group, twitter).

### Estimated potential reach:
250 million people (Russian speakers worldwide).

### Estimated actual impact:
~20.000-100.000 views/"reads".

### 🔗 Communities to share:
1) ["Всё о криптовалютах"](https://t.me/o_kripte) ("All about cryptocurrencies") [Telegram channel] (18k subscribers) - local crypto-media.
2) ["CriptoNews"](https://t.me/criptonewsss) [Telegram channel] (11k subscribers) - local crypto-media.
3) ["Bitconovosti"](https://t.me/bitco_novosti) [Telegram channel] (15k subscribers) - local crypto-media. 
4) ["Биткоин, Блокчейн, Ethereum"](https://t.me/EthereumIC) ("Bitcoin, Blockchain, Ethereum") [Telegram channel] (14k subscribers) - local crypto-media. 
5) ["Криптоник - Биткоин и Блокчейн"](https://t.me/electroniccurrency) ("Kryptonics - Bitcoin and Blockchain") [Telegram channel] (10k subscribers) - local crypto-media. 
6) ["MiningClub.info"](https://miningclub.info) [Forum] - popular crypto-forum.  
7) ["BitcoinTalk.org"](https://bitcointalk.org/index.php?board=10.0) [Forum] - russian-speaking forum thread.
8) ["ForkLog"](https://forklog.com) / ["BitNovosti"](https://bitnovosti.com) / ["IHODL"](https://ru.ihodl.com) / ["Bits.Media"](https://bits.media) - I will do my best to publish there. They are very popular Russian media.

**Comment by felipegaucho** [comment]
Hi @RaffiSapire,

🎆 Update: bounty completed 🎉 - 1st & 2nd milestone are done.

**1º**
✅ 25/01 (completed **28/01**): [Video Miner text localisation + Publication on local media](https://livecoins.com.br/o-que-fazer-com-suas-gpus-alem-de-apostar-na-criptomoeda-grin).
✅ 03/02 (completed **19/02**): [Streamflow WP translation (PT-BR)](https://github.com/felipegaucho/wiki-1/blob/master/STREAMFLOW.md).
✅ 07/02 (completed: **25/02**): [101 video re-recording (PT-BR)](https://youtu.be/sP_RgBZ6lJQ) [[text on GDrive](https://docs.google.com/document/d/1CW_-3U6OYaqKxifgelOk9fXkhx7QWTFcPgaFy5iXjDY/edit?usp=sharing)]. 

**2º**
✅ 25/01 (completed **05/04**): Present Livepeer on a [local](https://twitter.com/LivepeerOrg/status/1111688385624711169) [meetup](https://twitter.com/Felipether/status/1116071228605964289).
✅ 6/02 (completed **15 & 23/04**): [Text 2 publication on local media](https://cointimes.com.br/desmistificando-retornos-de-staking%EF%BB%BF/) (_focus on staking, inner workings, tools to stake, etc - some nice charts included_) + [Text 3 on local media](https://www.criptofacil.com/pewdiepie-abracou-a-blockchain-o-youtube-seguira-seus-passos) (_using PewDP migration as a news hook, focus on scaling, presenting 101 video & translated paper, Streamflow_).

------------------------------------------------------

Lengthy delay in the end, but:

- +15.9K words (2.725 [[1st text](https://livecoins.com.br/o-que-fazer-com-suas-gpus-alem-de-apostar-na-criptomoeda-grin)] + 7.894 [[paper](https://github.com/felipegaucho/wiki-1/blob/master/STREAMFLOW.md)] + 512 [[video](https://youtu.be/sP_RgBZ6lJQ)] + 3.334 [[2nd text](https://cointimes.com.br/desmistificando-retornos-de-staking%EF%BB%BF/)] + 1.496 [[3rd text](https://www.criptofacil.com/pewdiepie-abracou-a-blockchain-o-youtube-seguira-seus-passos)]);
- 1840 reads on 3 texts (until 04/23);
- 616 "direct engagements" (32 'native' likes on texts + 520 active workshop/course participants + 64 people in MeetUp);
- 4 mentions or explainers in videos, ~22.2k combined views ([portal interview](https://www.infomoney.com.br/mercados/bitcoin/noticia/7896383/bloco-cripto-bitcoin-tenta-encontrar-um-novo-suporte-e-as-projecoes-para-o-ethereum) -> 12.4k views || [private workshop](https://lp.infomoney.com.br/workshop_segredos-investir-certo-criptomoedas_transmissao?submissionGuid=c10bccc0-ca6a-497a-9914-eb2d0b1b6e34) on 3 tokens, 1 being LPT _(only open link is to the pitch)_ -> 1.6k views || [private course](https://lp.infomoney.com.br/workshop_altcoins-mais-quentes-2019_inscricao) _(idem)_ -> 520 views || [YTer channel](https://www.youtube.com/watch?v=D0C40xoxD6k) -> 7.7k views)

🎯 End impact is a little below the [projection I made](https://github.com/Livepeer-Community-Node/Grant-Program/issues/3#issuecomment-445282540), specifically _(as for views/reads)_. These will probably get into the projected range in a couple weeks.

📅 Timeline: wrapping it all up 4 weeks above the upper bound I estimated.

**Comment by RaffiSapire** [comment]
That is amazing @felipegaucho ! Thanks so much!! I just shared it in a brand new channel in portuguese. Sending you the LPT now.

**Comment by RaffiSapire** [comment]
@felipegaucho https://etherscan.io/tx/0x03064021145eca071a284d31804d1fb7cddec8a98bb78202743d03b98564b8c7

**Comment by RaffiSapire** [comment]
Hi @fedorello Awesome. Would love to get this going. 

M1. For Whitepaper, Streamflow and the Graph Day talk translated -  300 LPT (using March 30 day price average of 7.06. **  Hold off on the 101 video because we are re-doing the script - once I have new script would love to have your help :) 

Distribution: Content shared in the 10 communities listed, with a goal of engagement - 2 comments / questions from community in each! 6.5 LPT each.

**Comment by RaffiSapire** [comment]
Hey @GreyEcologist let us know if you need help with anything!

**Comment by GreyEcologist** [comment]
@RaffiSapire Hi Raffi, I should have an update next week, wrapping things up with the white paper translations. There are some formatting and linking work left, but almost there!

**Comment by fedorello** [comment]
Hi @RaffiSapire, so far, I’m on schedule:
✅ (7/05) [**Livepeer Whitepaper (in Russian)**](https://github.com/fedorello/wiki/blob/fedorello-patch-1/WHITEPAPER.md) - started 7 days ago.
🕒 **Livepeer Streamflow (in Russian)** - just begun.

**Comment by fedorello** [comment]
Just finished translating the Streamflow document.
✅ (7/05) [**Livepeer Whitepaper (in Russian)**](https://github.com/fedorello/wiki/blob/fedorello-patch-1/WHITEPAPER.md).
✅ (16/05) [**Livepeer Streamflow (in Russian)**](https://github.com/fedorello/wiki/blob/fedorello-patch-1/STREAMFLOW.md) - started 9 days ago.
🕒 **"Graph Day: Designing The Livepeer Protocol with Eric Tang"** video (in Russian) - just begun.

**Comment by RaffiSapire** [comment]
THanks for the update, @fedorello

**Comment by fedorello** [comment]
@RaffiSapire, I finally finished with the video.
✅ (7/05) [Livepeer Whitepaper (in Russian)](https://github.com/fedorello/wiki/blob/fedorello-patch-1/WHITEPAPER.md).
✅ (16/05) [Livepeer Streamflow (in Russian)](https://github.com/fedorello/wiki/blob/fedorello-patch-1/STREAMFLOW.md).
✅ (27/05) ["Graph Day: Designing The Livepeer Protocol with Eric Tang" video (in Russian)](https://youtu.be/YrLapFc1j2k) - started 11 days ago.

✋ Still haven't started translating the "Livepeer 101" video, as I am awaiting your confirmation. You said that a new script would be made. Though I'm ready to post translated content in communities, I don't wanna do this without the translated "Livepeer 101" video.

**Comment by GreyEcologist** [comment]
@RaffiSapire Hey Raffi! Took me longer than expected but I'm done with the paper translations:
✅ (05/29) [Livepeer Whitepaper (French)](https://github.com/GreyEcologist/wiki/blob/feature/french_translation/WHITEPAPER_FRENCH.md).
✅ (05/29) [Livepeer Streamflow (French)](https://github.com/GreyEcologist/wiki/blob/feature/french_translation/STREAMFLOW_FRENCH.md).

Next is the "Livepeer 101" video. Planning to do it this weekend, but I'll keep an eye on this thread.

Best.

**Comment by GreyEcologist** [comment]
@felipegaucho I see you created your own slides for the Livepeer 101 video. Looks almost the same as the original. What tool did you use to create it?

**Comment by felipegaucho** [comment]
Hi @GreyEcologist ! It was Keynote.

You can find an open version of the file [here](https://we.tl/t-pJQGqbCiTS) (not beautiful/clean - but works fine for translating/adapting/exporting static files).

Feel free to ping me if the link expires or you need something.

Best,

**Comment by PetSte** [comment]
Dear @RaffiSapire,

I would like to apply for a LivePeer Community Grant.

**Objective:**

Provide the Dutch speaking community with all the documents needed to start off with Livepeer.

**Why the Dutch speaking community?**

Because the Netherlands (aka Holland) is one the top countries in the world when it comes to blockchain/cryptocurrency adoption and innovation, and its government and regulations make for quite a favorable entrepreneurial climate. It might be a small country with a population of only 17 million, but its reach is far and wide; you will find my countrymen all over the world.

**Tasks**

Translate the Livepeer whitepaper into Dutch.
Translate the Streamflow whitepaper into Dutch.
Create a Dutch script/subtitles for the Livepeer 101 video.
_Translate other documents at the request of LivePeer._

**Timeframe**

I think I need about 20 hours for both whitepapers each and only a couple for the subtitles, for a total maximum of 50 hours. If needed I can complete this job in a couple of weeks.

**Qualifications:**

I have a background in both blockchain consulting as well as copy editing/translating academic articles, a combination that seems perfect for this kind of job. If you want I can send you a link to my LinkedIn page in private.

**Impact:**

I don’t yet have a concrete plan with whom I’m going to share the results. Of course the documents can be added to the general LivePeer knowledge database (on the site and on GitHub). If wanted I can share it with my clients in person and via my LinkedIn (I am connected with quite some (influential) people in the crypto community). I’m also thinking of maybe doing a presentation on LivePeer in one of my crypto meetups (not an official Meetup, but a casual get-together with (prospective) clients). I am of course open to all kinds of suggestions.

Would love to hear from you.

**Comment by GreyEcologist** [comment]
@RaffiSapire Hey Raffi, I am done with the first milestone of the grant, below is a link to the french version of the Livepeer 101 video:

✅ (completed 06/27) [Livepeer 101 (French)](https://www.youtube.com/watch?v=LNb-9pAsEIU).

I have the video unlisted, will wait for your feedback and also to coordinate with the second part. For the milestone, I will be reaching out to french media outlet over the weekend and post the results here. Also, I will be traveling to France after this summer, will be looking to book an event once I'm there.\

Best.

**Comment by RaffiSapire** [comment]
Looks great, @GreyEcologist ! LMK when it is public, and I will share on social media!! What is your eth address? Will send you 400 LPT. Thank you for this fantastic work! LMK if you want to check in on the phone and talk more aobut livepeer/ community stuff in July :)

**Comment by RaffiSapire** [comment]
@fedorello What is your ETH address? Will send you 300 LPT as discussed for M1. Thank you for all your great work!! Cannot wait to showcase this to the community.

**Comment by RaffiSapire** [comment]
@fedorello  Could you please post in the russian channel in our discord, and share the resources you made?

**Comment by fedorello** [comment]
@RaffiSapire Here's my ETH address for LPT - 0xB1Ab0a062a405a2E746084c6Be56c3E702DB2F5f
I'll share the resources I've made in the russian channel in the coming days.

**Comment by RaffiSapire** [comment]
@GreyEcologist paid for m1 https://etherscan.io/tx/0x8fda0c3f0d73137ac05e023348933eed00e174c43bbba042012d116a15857eab 

THank you!

**Comment by fedorello** [comment]
Hey @RaffiSapire! Still awaiting reward for M1. Also I've written press release and sent it to various communities which I mentioned earlier. As soon as there is a result, I'll inform you.

**Comment by RaffiSapire** [comment]
done @fedorello . Have you posted in the appropriate community channel? https://etherscan.io/tx/0xad195b4f6a9f295f029707e416a4fde68ef7fdbc3d0b10c5ca231b811f1b6612

**Comment by adamsoffer** [comment]
Hey @felipegaucho @GreyEcologist and @fedorello! We have an [open grant](https://github.com/livepeer/Grant-Program/issues/19) for translating the [livepeer.org](https://livepeer.org) website in your respective languages. Are any of you interested in applying? If so please feel free to respond to the grant issue. Thanks!
